CREATE TABLE loginginfo (
  username varchar(100) DEFAULT NULL,
  password varchar(100) DEFAULT NULL,
  role varchar(100) DEFAULT NULL,
  request varchar(1000) DEFAULT NULL,
  response varchar(1000) DEFAULT NULL,
  loggingtime TIMESTAMP(100) DEFAULT NULL
);


CREATE TABLE roles (
  username varchar(50) NOT NULL,
  name varchar(50) NOT NULL
);


CREATE TABLE users (
  id numeric(11) NOT NULL,
  email varchar(50) NOT NULL,
  password varchar(64) NOT NULL
);


Insert into users ("id","email","password") values (1,'santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC');
Insert into users ("id","email","password") values (2,'sant@gmail.com','$2a$10$adlOYZlNh3n.zI8npsYHtOX/4jiHxZlzZZ4lqarN9rJyKsafuicR2');


Insert into roles ("name","username") values ('ROLE_USER','sant@gmail.com');
Insert into roles ("name","username") values ('ROLE_ADMIN','santoshm@gmail.com');



Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTQ5Nzc5OTMsImV4cCI6MTY1NTA2NDM5M30.eCUB84yWat0Pr6J1GvfiemGVFtJjle_le9OL-Tn4f7IK7m3Kp7Grm-kiRTgLU8Q4LZveZcW8VGW9JEFZxbeDPg]',to_timestamp('2022-06-12 01:36:33.94','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('sant@gmail.com','$2a$10$adlOYZlNh3n.zI8npsYHtOX/4jiHxZlzZZ4lqarN9rJyKsafuicR2','[ROLE_EDITOR]','AuthRequest [email=sant@gmail.com, password=santosh]','AuthResponse [email=sant@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLHNhbnRAZ21haWwuY29tIiwiaXNzIjoiQ29kZUphdmEiLCJ1c2VybmFtZSI6InNhbnRAZ21haWwuY29tIiwicm9sZXMiOiJbUk9MRV9FRElUT1JdIiwiaWF0IjoxNjU0OTc4MTcxLCJleHAiOjE2NTUwNjQ1NzF9.fI2RLkJeGHpU-13zyRVzZV-O0RkkKJTiRRGxYOQlMJzUXlk99ktfMgY9o0tKsuAKXqvMLOEvQvR9U_LhMmh12Q]',to_timestamp('2022-06-12 01:39:31.857','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('sant@gmail.com','$2a$10$adlOYZlNh3n.zI8npsYHtOX/4jiHxZlzZZ4lqarN9rJyKsafuicR2','[ROLE_EDITOR]','AuthRequest [email=sant@gmail.com, password=santosh]','AuthResponse [email=sant@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLHNhbnRAZ21haWwuY29tIiwiaXNzIjoiQ29kZUphdmEiLCJ1c2VybmFtZSI6InNhbnRAZ21haWwuY29tIiwicm9sZXMiOiJbUk9MRV9FRElUT1JdIiwiaWF0IjoxNjU0OTc5MDE1LCJleHAiOjE2NTUwNjU0MTV9.rwsZQymx9forMW9aiAh932KuMc233IXLnX3Q4yyJ-Kc4wGEk8oHLCJPYBw7dbCZr23NO8A9MJm9iijxSCHiwjA]',to_timestamp('2022-06-12 01:53:35.906','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTQ5NzkxNDksImV4cCI6MTY1NTA2NTU0OX0.mPLidSnlTrnRCMhuYI2I1C3olhBRoD_vdmsxZxHGKdpdUDJs89XxEGBJtqEGTN6p90m22ocKkyDeo83jU_-qIg]',to_timestamp('2022-06-12 01:55:49.379','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTQ5ODAyODYsImV4cCI6MTY1NTA2NjY4Nn0.vXClMOKDNRYy9f261g3MMzFSCwccHRs3IOlJhpJcxAt95_5CAHkbDiiD8p6X5zpJhdmdzV52jh07YpbP8o-rBQ]',to_timestamp('2022-06-12 02:14:46.995','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6ImFkbWluIiwiaWF0IjoxNjU0OTgwNjgyLCJleHAiOjE2NTUwNjcwODJ9.16CG4ArugfvpSFxQKXwRzMimhMiqsDv0-WTq0OEjcrdpuPvr9AFlxNOV-SRwFQDDPnBQkQxOsJuMTKT2aW5jlw]',to_timestamp('2022-06-12 02:21:22.089','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTQ5ODEyNDgsImV4cCI6MTY1NTA2NzY0OH0.dqTb8E4PUuwiEQrKmphvWVJ_nMhqJQEENZfnlNBjlR5IqPZJN_abAU8FoDX9NAgAAcZk5yFv-ruWI1rVJwnYyw]',to_timestamp('2022-06-12 02:30:48.825','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTUwMDcxMDIsImV4cCI6MTY1NTA5MzUwMn0.j5M2qKikF34yMTJKFUdNFC0cTX33UWjwKa-RVh_V7vSMMCbIzojdyF9MKynLiFdVe7YZVzeI8MkvyOkWpkh1_A]',to_timestamp('2022-06-12 09:41:42.385','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTUwMDg0MzUsImV4cCI6MTY1NTA5NDgzNX0.Zr4p9hF4gOdM-EMOtN6HF968XMnJ8MIyXHXsxdyVuQQV5GJ-fASwhoWfr6zOLx35SNZ0k5UldFxt8VlntvQ0UQ]',to_timestamp('2022-06-12 10:03:55.45','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTUwMDg5MTEsImV4cCI6MTY1NTA5NTMxMX0.Yztpe2P5oAtDAjHq3-9t4VyDcogeMFcavZmyfwDtgRQ0WJipBVNQCvxva6CedNdS3-APg7aTEyigQERAkhrZYQ]',to_timestamp('2022-06-12 10:11:51.439','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTUwMTAyMjgsImV4cCI6MTY1NTA5NjYyOH0._gt6ND8xuPWjzaC_6QswQz5uJbrLCSiheQkc-ZBv6uy1mos8NdOn51T_15L5X0QsPJs2uSq0pEYerUKVVMuhIA]',to_timestamp('2022-06-12 10:33:48.025','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTUwMTEyNzAsImV4cCI6MTY1NTA5NzY3MH0.cwC0nJDBMNh0MLAciR8MAEq4jcWtrSbt4WHoY42UCMkQecYNoEvOLsVMmkh-vF4nAI5KWmMWCjScXW3-z5xGog]',to_timestamp('2022-06-12 10:51:10.116','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTUwMTE1NjcsImV4cCI6MTY1NTA5Nzk2N30.QTXUYfG8t35PKO1sHGm_ECucFt2sEajopBRyi1Asb1Q5a-pzsSAb2F_FZmVzvojZJ_4asmg-B2-GqAYsNEZf_g]',to_timestamp('2022-06-12 10:56:07.727','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('sant@gmail.com','$2a$10$adlOYZlNh3n.zI8npsYHtOX/4jiHxZlzZZ4lqarN9rJyKsafuicR2','[ROLE_EDITOR]','AuthRequest [email=sant@gmail.com, password=santosh]','AuthResponse [email=sant@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLHNhbnRAZ21haWwuY29tIiwiaXNzIjoiQ29kZUphdmEiLCJ1c2VybmFtZSI6InNhbnRAZ21haWwuY29tIiwicm9sZXMiOiJbUk9MRV9FRElUT1JdIiwiaWF0IjoxNjU1MDE5OTc0LCJleHAiOjE2NTUxMDYzNzR9.7fBE9AT8l2-e07P1vNifIliLWtL14EzFaGizzLksz4k8wywxZTqo49I7N-4rqm4keVdX4qEWQg5Z0a967UIpGg]',to_timestamp('2022-06-12 13:16:14.107','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTUwMjAwMjMsImV4cCI6MTY1NTEwNjQyM30.1LOUWPb4E59JBthkPSJ0P02yuQU8OZsCRXV-N8-TGYdVf3yUxPKv5tk9sbVVrYDScf-fcjaWNEp5fvEQA_Z3_g]',to_timestamp('2022-06-12 13:17:03.278','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTUwMjAxODQsImV4cCI6MTY1NTEwNjU4NH0.VgzzyPxKGkBzSjF1fnuTeiUiSHqnyo5VQ3zX8akTbjquJSS6zrhYxr1rrgTbsdOcRvLXUwB4u9XP-k1AKrrJjg]',to_timestamp('2022-06-12 13:19:44.876','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[admin]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IlthZG1pbl0iLCJpYXQiOjE2NTUwMjAxOTgsImV4cCI6MTY1NTEwNjU5OH0.Dr1OVuYysFaqXoJ7MWjNrbKWO3e3AqCoSKkvmpeZUZKeTULKZyO6ZA5ErAdnUnm_o-o-6jPXXDoKci7-VdSYlA]',to_timestamp('2022-06-12 13:19:58.839','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('sant@gmail.com','$2a$10$adlOYZlNh3n.zI8npsYHtOX/4jiHxZlzZZ4lqarN9rJyKsafuicR2','[ROLE_EDITOR]','AuthRequest [email=sant@gmail.com, password=santosh]','AuthResponse [email=sant@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLHNhbnRAZ21haWwuY29tIiwiaXNzIjoiQ29kZUphdmEiLCJ1c2VybmFtZSI6InNhbnRAZ21haWwuY29tIiwicm9sZXMiOiJbUk9MRV9FRElUT1JdIiwiaWF0IjoxNjU1MDIwMzUxLCJleHAiOjE2NTUxMDY3NTF9.bOCwFZv-m0eSpYC7gh8mpIWTkgFCyvgKmMBZryOF2NxRl-CdbTqFA4ugssV7fbXuiI3BqqtRHBYaw90uLnDHxw]',to_timestamp('2022-06-12 13:22:31.95','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('sant@gmail.com','$2a$10$adlOYZlNh3n.zI8npsYHtOX/4jiHxZlzZZ4lqarN9rJyKsafuicR2','[ROLE_EDITOR]','AuthRequest [email=sant@gmail.com, password=santosh]','AuthResponse [email=sant@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLHNhbnRAZ21haWwuY29tIiwiaXNzIjoiQ29kZUphdmEiLCJ1c2VybmFtZSI6InNhbnRAZ21haWwuY29tIiwicm9sZXMiOiJbUk9MRV9FRElUT1JdIiwiaWF0IjoxNjU1MDIwNTAwLCJleHAiOjE2NTUxMDY5MDB9.yFz_ihgiV3fpR8g6R1qm4kln3yGus5mFPxe3roorAruRaol_GCLgYKBq3Eb27qET6fv22ySm_wQvT9Se8yi_8g]',to_timestamp('2022-06-12 13:25:00.311','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[ADMIN]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IltBRE1JTl0iLCJpYXQiOjE2NTUwMjA1MDIsImV4cCI6MTY1NTEwNjkwMn0.NZt9NPbkqIZ2j8-gg7fO63k9vLsSAbMnhSfyhnKgek-UCQ7N8fYT5Q0YtNNzRLaIfIxLJslc_f0O3vTtfOA3Aw]',to_timestamp('2022-06-12 13:25:02.949','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[ADMIN]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IltBRE1JTl0iLCJpYXQiOjE2NTUwMjA1NDMsImV4cCI6MTY1NTEwNjk0M30.y4cKurvHmZiLQwh7OwtQDLh5G7ORvORXn-S3lHO1JZ_vfZ9xPnrLToBDukB45EPXAtICPYD_gBV5R9I77LyDCQ]',to_timestamp('2022-06-12 13:25:43.038','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[ADMIN]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IltBRE1JTl0iLCJpYXQiOjE2NTUwMjA2OTMsImV4cCI6MTY1NTEwNzA5M30.JrZDMYC68g2GXOd4xlN1nGVIxdWDF10P1lcss0VAOrNpjkZWt51Uu0GHRcpCSuOiX-NXlNfUWCnTzdu4Y9Rx-g]',to_timestamp('2022-06-12 13:28:13.403','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('sant@gmail.com','$2a$10$adlOYZlNh3n.zI8npsYHtOX/4jiHxZlzZZ4lqarN9rJyKsafuicR2','[ROLE_EDITOR]','AuthRequest [email=sant@gmail.com, password=santosh]','AuthResponse [email=sant@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLHNhbnRAZ21haWwuY29tIiwiaXNzIjoiQ29kZUphdmEiLCJ1c2VybmFtZSI6InNhbnRAZ21haWwuY29tIiwicm9sZXMiOiJbUk9MRV9FRElUT1JdIiwiaWF0IjoxNjU1MDIwNzA3LCJleHAiOjE2NTUxMDcxMDd9.Ng1LGeeKZGHRBsNpW-sXMcSFs7OrrrWAukM3pXPwCdmjIWegHfNZFqwktu-6DfeATxYOflHI_74r4YrhpC1ZWA]',to_timestamp('2022-06-12 13:28:27.335','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[ROLE_ADMIN]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IltST0xFX0FETUlOXSIsImlhdCI6MTY1NTAyMTE1OSwiZXhwIjoxNjU1MTA3NTU5fQ.Sd72nEOGI8UuRlD0ZiTtlcr1uiprHfNQyWv7EAUvRtr8MccJQkqSVBrTmGTKR3ZVKq0EuCFDC-9ExRwYfSNrNA]',to_timestamp('2022-06-12 13:35:59.578','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[ROLE_ADMIN]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IltST0xFX0FETUlOXSIsImlhdCI6MTY1NTAyMTI3NiwiZXhwIjoxNjU1MTA3Njc2fQ.t3VezKOsCqFKv3KJTh03MFIfUI1r8wV4SxVsr0HjbxJ_A5N-08qIYexn8EEGhED3yifauydXysgRASWvcKDOYw]',to_timestamp('2022-06-12 13:37:56.339','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('sant@gmail.com','$2a$10$adlOYZlNh3n.zI8npsYHtOX/4jiHxZlzZZ4lqarN9rJyKsafuicR2','[ROLE_USER]','AuthRequest [email=sant@gmail.com, password=santosh]','AuthResponse [email=sant@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLHNhbnRAZ21haWwuY29tIiwiaXNzIjoiQ29kZUphdmEiLCJ1c2VybmFtZSI6InNhbnRAZ21haWwuY29tIiwicm9sZXMiOiJbUk9MRV9VU0VSXSIsImlhdCI6MTY1NTAyMTMxNywiZXhwIjoxNjU1MTA3NzE3fQ._D7Nr9m4JeIPaL9sdjhxyqrcNyD5d3bSf0vztTewF0_vQilt8wWu_MRSiATO3evbriciakjDoFSv3M1L4IjWhA]',to_timestamp('2022-06-12 13:38:37.27','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$6dHv80hpO9GntOH/hKocY.4O6RDRG/esvt9Oh3.W3wdToCpMP4wYC','[ROLE_ADMIN]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IltST0xFX0FETUlOXSIsImlhdCI6MTY1NTAyMzU2OSwiZXhwIjoxNjU1MTA5OTY5fQ.8Sj1I-WWB7vJy64LpnLgYGOscZYvgJ4V47cyQQ9Hj4Cg07NqA797PA5lIOHhkn5DZ_1qovKmYq07U0UZsXZJJQ]',to_timestamp('2022-06-12 14:16:09.286','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('sant@gmail.com','$2a$10$adlOYZlNh3n.zI8npsYHtOX/4jiHxZlzZZ4lqarN9rJyKsafuicR2','[ROLE_USER]','AuthRequest [email=sant@gmail.com, password=santosh]','AuthResponse [email=sant@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLHNhbnRAZ21haWwuY29tIiwiaXNzIjoiQ29kZUphdmEiLCJ1c2VybmFtZSI6InNhbnRAZ21haWwuY29tIiwicm9sZXMiOiJbUk9MRV9VU0VSXSIsImlhdCI6MTY1NTAyNDIyMSwiZXhwIjoxNjU1MTEwNjIxfQ.fbPx7HRsdvX4FXipv9SSOW5tLkmHJdTDRxxUbkAIo_vtnuGzZuv9IhTJWUVftdaxSwYS8CwCIvG1UaVbSpSp0g]',to_timestamp('2022-06-12 14:27:01.296','null'));
Insert into loginginfo ("username","password","role","request","response","loggingtime") values ('santoshm@gmail.com','$2a$10$ZDI3RgrY6Hg5DCKZzh.ITeykwqU.bTE3V5EQK5NZ7I6AfKNv0kCYW','[ROLE_ADMIN]','AuthRequest [email=santoshm@gmail.com, password=santosh]','AuthResponse [email=santoshm@gmail.com, accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHNhbnRvc2htQGdtYWlsLmNvbSIsImlzcyI6IkNvZGVKYXZhIiwidXNlcm5hbWUiOiJzYW50b3NobUBnbWFpbC5jb20iLCJyb2xlcyI6IltST0xFX0FETUlOXSIsImlhdCI6MTY1NTAyNTM4NCwiZXhwIjoxNjU1MTExNzg0fQ.oaaGtOeNcaBFpFdmpQE-GKl6Dgln4WYTjzMW7yBgTxRK5GpOhoNQRJ2eB4FwTZnT3yrpvT6k-vilguWsTCJuyg]',to_timestamp('2022-06-12 14:46:24.123','null'));
